name: Release pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to deploy policies to?
        type: choice
        required: true
        options:
          - production
          - test
          - development
      policy:
        description: Which policy file to deploy?
        type: string
        required: true
      acl:
        description: Associated ACL to publish with policy? (Leave blank for none)
        type: string
      inherit_from:
        description: Which policy should this one override?
        type: string

jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-verion: [ 3.10 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r requirements.txt

      - name: Production Deploy Setup
        if: github.event.inputs.environment == 'production'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_PROD_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PROD_TOKEN }}
        run: |
          python deploy.py

      - name: Test Deploy Setup
        if: github.event.inputs.environment == 'test'

        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_TEST_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TEST_TOKEN }}
        run: |
          python deploy.py

      - name: Development Deploy Setup
        if: github.event.inputs.environment == 'development'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
        run: |
          python deploy.py
